In [1]:

import math
def InitialDataReducedMass(orbitalangle,r0):
    phi=orbitalangle
    radiusseparation=r0 #separation one hundred
    eccentricity=np.zeros(2)
    mass=np.ones(2)
    masssun=1.989*10**30
    lsun=3.828*10**26
    massearth=5.9722*10**24
    masses=mass #*masssun (natural units)
    return phi, radiusseparation,eccentricity, masses
    

In [2]:
def getxyuveqreducedmass(initdat): #using reduced mass cooordinate system
    phi,radiusseparation,eccentricity, masses=initdatreducedmass
    #print(orbitalradius, phi, np.cos(phi), np.sin(phi))
    metersperAU=1
    Gconstant=1
    x0=np.zeros(2)
    y0=np.zeros(2)
    x0[1]=radiusseparation*np.cos(phi)*metersperAU
    y0[1]=radiusseparation*np.sin(phi)*metersperAU
    if phi==0:
        print("zero")
        x0[1]=radiusseparation
        y0[1]=0
    if phi==math.pi:
        print("pi")
        x0[1]=-radiusseparation
        y0[1]=0
    z0=np.zeros(2)
    print("x0", x0)
    print("y0", y0)
    
    #start at perihelion for both (eliptical, doesn't generalize to three body)
    #actually start with circular orbit
    ux0=np.zeros(2) #*149597870700
    #centrepital force balances gravitational force
    reducedmass=np.zeros(2)
    masstotal=np.sum(masses)
    reducedmass[0]=masstotal
    print(masses)
    for i in np.arange(1):
        j=(i+1)%2 #reverse masses
        reducedmass[i+1]=masses[i]*masses[j]/np.sum(masses)
    print(reducedmass)
    metersperAU=1 #natural units
    rphys=np.zeros(len(masses))
    for i in np.arange(2):
        #rphys is r in the reduced mass system
        rphys[i]=radiusseparation #*metersperAU*reducedmass[i]/masses[i]
    x0[0]=0.0
    x0phys=rphys*x0/radiusseparation
    x0phys[0]=0.0
    y0phys=rphys*y0/radiusseparation
    z0phys=np.zeros(2)
    r0=np.sqrt(x0**2+y0**2)
    print(rphys)
    #G=1
    Gconstant=1
    F=(Gconstant*masstotal**2/(2*rphys)**2)
    print(F)
    #centF=reducedmass*v**2/rphys
    #centF=accel
    v=np.sqrt(Gconstant*masstotal/(rphys))
    print(v)
    print("r0", r0)
    ux0=-v*y0/radiusseparation #[1]
    uy0=v*x0/radiusseparation #[1]
        
    #ux0=-v*y0/r0
    #uy0=v*x0/r0 #initial data in y only
    #evolve in plane only
    #circular orbit
    uz0=np.zeros(2)
    
    a=Gconstant*masstotal/((2*rphys)**2)
    ax0=-a*x0/radiusseparation
    ay0=-a*y0/radiusseparation
    az0=np.zeros(2)
    
    statevec=[]
    avec=[]
    for i in np.arange(len(x0phys)):
        stateveci=np.array([x0phys[i],y0phys[i],z0phys[i],ux0[i],uy0[i],uz0[i]])
        aveci=np.array([ax0[i],ay0[i],az0[i]])
        statevec.append(stateveci)
        avec.append(aveci)
    statevecnp=np.array(statevec)
    avecnp=np.array(avec)
    return masstotal, reducedmass,statevecnp,avecnp

In [3]:
import random,numpy as np
initdatreducedmass=InitialDataReducedMass(0,50)

In [4]:
xyuvaeqreducedmass=getxyuveqreducedmass(initdatreducedmass)
print(xyuvaeqreducedmass)
masstotal, reducedmass,xvec,avec=xyuvaeqreducedmass

zero
x0 [ 0. 50.]
y0 [0. 0.]
[1. 1.]
[2.  0.5]
[50. 50.]
[0.0004 0.0004]
[0.2 0.2]
r0 [ 0. 50.]
(2.0, array([2. , 0.5]), array([[ 0. ,  0. ,  0. , -0. ,  0. ,  0. ],
       [50. ,  0. ,  0. , -0. ,  0.2,  0. ]]), array([[-0.    , -0.    ,  0.    ],
       [-0.0002, -0.    ,  0.    ]]))


In [5]:
xvec[:,2]

array([0., 0.])

In [6]:
axii=np.zeros(len(xvec[:,0]))
rii=np.sqrt(xvec[:,0]**2+xvec[:,1]**2+xvec[:,2]**2)
rii=np.sqrt(xvec[:,0]**2+xvec[:,1]**2+xvec[:,2]**2)
rii

array([ 0., 50.])

In [7]:
def RK4implicit(h,t,xvec,f): #not a finite difference so no step in y
    k1= h*f(t,xvec)
    k2=h*f(t+h/2, xvec+k1/2)
    k3=h*f(t+h/2,xvec+k2/2)
    k4=h*f(t+h,xvec+k3)
    return t+h, xvec+1/6.*(k1+2.*k2+2.*k3+k4)

In [8]:
class OrbitDiffEq:
    def __init__(self,reducedmass,xvec,avec,t0):
        self.reducedmass=reducedmass
        self.xvec=xvec
        self.ti=t0
        self.avec=avec
    def dxidt(self,t,xvec):
        return xvec[:,3].transpose()
    def dyidt(self,t,xvec):
        return xvec[:,4].transpose()
    def dzidt(self,t,xvec):
        return xvec[:,5].transpose()
    def dvxidt(self,t,xvec):
        #return axi[m]
        axii=np.zeros(len(xvec[:,0]))
        rii=np.sqrt(xvec[:,0]**2+xvec[:,1]**2+xvec[:,2]**2)
        Gconstant=1 #6.408*10**-11
        for k in np.arange(len(rii)):
            for j in np.arange(1,len(rii)):
                if j==0:
                    axii[j]=0.0
                if j!=k:
                    rreljk=np.abs((xvec[j,0] - xvec[k,0])**2+(xvec[j,1]-xvec[k,1])**2+(xvec[j,2]-xvec[k,2])**2)**(1./2.)
                    axii[j]-=Gconstant*self.reducedmass[k]*(xvec[j,0]  - xvec[k,0])/rreljk**3
        return axii
    def dvyidt(self,t,xvec):
        #return axi[m]
        ayii=np.zeros(len(xvec[:,0]))
        rii=np.sqrt(xvec[:,0]**2+xvec[:,1]**2+xvec[:,2]**2)
        Gconstant=1 #6.408*10**-11
        for k in np.arange(len(rii)):
            for j in np.arange(1,len(rii)):
                if j==0:
                    ayii[j]=0.0
                if j!=k:
                    rreljk=np.abs((xvec[j,0] - xvec[k,0])**2+(xvec[j,1]-xvec[k,1])**2+(xvec[j,2]-xvec[k,2])**2)**(1./2.)
                    ayii[j]-=Gconstant*self.reducedmass[k]*(xvec[j,1]  - xvec[k,1])/rreljk**3
        return ayii
    def dvzidt(self,t,xvec):
        #return axi[m]
        azii=np.zeros(len(xvec[:,0]))
        rii=np.sqrt(xvec[:,0]**2+xvec[:,1]**2+xvec[:,2]**2)
        Gconstant=1 #6.408*10**-11
        for k in np.arange(len(rii)):
            for j in np.arange(1,len(rii)):
                if j==0:
                    azii[j]=0.0
                if j!=k:
                    rreljk=np.abs((xvec[j,0] - xvec[k,0])**2+(xvec[j,1]-xvec[k,1])**2+(xvec[j,2]-xvec[k,2])**2)**(1./2.)
                    azii[j]-=Gconstant*self.reducedmass[k]*(xvec[j,2]  - xvec[k,2])/rreljk**3
        return azii
    
    def dvecdt(self,t,xvec):
        avec=np.array([self.dvxidt(self,xvec),self.dvyidt(self,xvec),self.dvzidt(self,xvec)])
        avecT=avec.transpose()
        self.avec=avecT
        dvec2=np.array([self.dxidt(t,xvec),self.dyidt(t,xvec),self.dzidt(self,xvec),avec[0,:],avec[1,:],avec[2,:]])
                       
        dvec2T=dvec2.transpose()
        return dvec2T
    def updateINTERNAL(self,xvecii,tii):
        self.xvec=xvecii
        self.ti=tii
        return self
    def update(self,xvecii,avecii,tii):
        self.xvec=xvecii
        self.avec=avecii,
        self.ti=tii
    def print2D(self):
        print(self.reducedmass,self.xvec[1], self.ti)
        return self
    def list2D(self):
        return self.reducedmass,self.xvec,self.avec,self.ti
    def timestepRK4ODE(self,step,dt):

    
        h=dt
        #tnew,ynew, intval=RK4(h,t,y,f)
        #m represents choices of mass
        i=step
        
        tnew,intvalxvec=RK4implicit(h,self.ti,self.xvec,self.dvecdt)
        #xii = intvalx
        #tnew,intvalvx=RK4implicit(h,self.ti,self.vxi,self.dvxidt)
        #vxii=intvalvx
        #tnew,intvaly=RK4implicit(h,self.ti,self.yi,self.dyidt)
        #yii = intvaly
        #tnew,intvalvy=RK4implicit(h,self.ti,self.vyi,self.dvyidt)
        #vyii=intvalvy
        #tnew,intvalz=RK4implicit(h,self.ti,self.zi,self.dzidt)
        #zii = intvalz
        #tnew,intvalvz=RK4implicit(h,self.ti,self.vzi,self.dvzidt)
        #vzii=intvalvz
        #axii=self.dvxidt(self.ti,np.zeros(np.shape(self.xi)))
        #ayii=self.dvyidt(self.ti,np.zeros(np.shape(self.yi)))
        #azii=self.dvzidt(self.ti,np.zeros(np.shape(self.zi)))
 
        #print(xii)
        self.updateINTERNAL(intvalxvec,tnew)
        return reducedmass, self.xvec,self.avec,self.ti

In [9]:
mtotal,reducedmass,xvec,avec=xyuvaeqreducedmass
ODEeq= OrbitDiffEq(reducedmass,xvec,avec,0.0)
ODEeq.print2D()
ODEeq.print2D()

[2.  0.5] [50.   0.   0.  -0.   0.2  0. ] 0.0
[2.  0.5] [50.   0.   0.  -0.   0.2  0. ] 0.0


In [10]:
dt=1 #natural units #*31556926 #seconds per year
numsteps=3000
mtotal, reducedmass,xvec0,avec0=xyuvaeqreducedmass
ODEeq= OrbitDiffEq(reducedmass,xvec0,avec0,0.0)
ODEeq.print2D()
t=0.0
star1x=[]
star2x=[]
star1a=[]
star2a=[]
times=[]
for i in np.arange(1,numsteps):
    reducedmass,xvec,avec,t=ODEeq.timestepRK4ODE(i,dt)
    if i< 10:
        ODEeq.print2D()
    star1x.append(xvec[0])
    star2x.append(xvec[1])
    star1a.append(avec[0])
    star2a.append(avec[1])
    times.append(t)



[2.  0.5] [50.   0.   0.  -0.   0.2  0. ] 0.0
[2.  0.5] [ 4.99996000e+01  1.99999467e-01  0.00000000e+00 -7.99997867e-04
  1.99998400e-01  0.00000000e+00] 1.0
[2.  0.5] [ 4.99984000e+01  3.99995733e-01  0.00000000e+00 -1.59998293e-03
  1.99993600e-01  0.00000000e+00] 2.0
[2.  0.5] [ 4.9996400e+01  5.9998560e-01  0.0000000e+00 -2.3999424e-03
  1.9998560e-01  0.0000000e+00] 3.0
[2.  0.5] [ 4.99936001e+01  7.99965867e-01  0.00000000e+00 -3.19986347e-03
  1.99974401e-01  0.00000000e+00] 4.0
[2.  0.5] [ 4.99900003e+01  9.99933335e-01  0.00000000e+00 -3.99973334e-03
  1.99960001e-01  0.00000000e+00] 5.0
[2.  0.5] [ 4.99856007e+01  1.19988480e+00  0.00000000e+00 -4.79953921e-03
  1.99942403e-01  0.00000000e+00] 6.0
[2.  0.5] [ 4.99804013e+01  1.39981707e+00  0.00000000e+00 -5.59926830e-03
  1.99921605e-01  0.00000000e+00] 7.0
[2.  0.5] [ 4.99744022e+01  1.59972695e+00  0.00000000e+00 -6.39890779e-03
  1.99897609e-01  0.00000000e+00] 8.0
[2.  0.5] [ 4.99676035e+01  1.79961123e+00  0.00000000e+

In [11]:
npstar2x=np.array(star2x)
npstar1x=np.array(star1x)
npstar2a=np.array(star2a)
npstar1a=np.array(star1a)
nptimes=np.array(times)

In [12]:
from bokeh.io import output_notebook, show
from bokeh.plotting import figure
output_notebook()
# create a new plot with default tools, using figure
p = figure(title="Circular orbit, RK4", plot_width=400, plot_height=400)

# add a circle renderer with x and y coordinates, size, color, and alpha
p.circle(npstar1x[:,0],npstar1x[:,1], size=15, line_color="purple",fill_color="purple", fill_alpha=0.5, legend="M")
p.line(npstar2x[:,0],npstar2x[:,1], line_color="blue", legend="mu")


p.legend.location = "bottom_left"
p.legend.click_policy="hide"

show(p) # show the

Loading BokehJS ...

%%html
<a href="https://github.com/sdorsher/ManyBodyProblem/blob/master/reduced%20mass%20circular%20orbit%20rk4.png"> Circular orbit in the reduced mass system </a> 
Note that the central heavier mass is stationary in this reference frame with the smaller lighter mass orbits about it in a circular orbit. 

In [13]:
from bokeh.io import output_notebook, show
from bokeh.plotting import figure
output_notebook()
# create a new plot with default tools, using figure
p = figure(title="X-acceleration, Circular orbit, RK4", plot_width=400, plot_height=400)

# add a circle renderer with x and y coordinates, size, color, and alpha
p.circle(times,npstar1a[:,0], size=1, line_color="purple",fill_color="purple", fill_alpha=0.5, legend="M")
p.circle(times,npstar2a[:,0], size=1, line_color="blue", legend="mu")

p.legend.location = "bottom_left"
p.legend.click_policy="hide"

show(p) # show the

Loading BokehJS ...

%%html
<a href="https://github.com/sdorsher/ManyBodyProblem/blob/master/reduced%20mass%20acceleration%20circular%20RK4.png">Acceleration in the reduced mass reference frame for a circular orbit </a> 

In the reduced mass reference frame, the acceleration of the larger mass is zero and the acceleration of the x componenet of the smaller mass is sinusiodal. 

In [14]:
def RunFirstOrbit(dt,initcondition,printoutput):
    masstotal,mass0,xvec, avec=initcondition
    x0=xvec[1,0]
    y0=xvec[1,1]
    lastvalue=[1,1]
    thisvalue=[xvec[1,0],xvec[1,1]]
    i=1
    t=0
    while not (lastvalue[0]>0 and lastvalue[1]<0 and thisvalue[0]> 0 and thisvalue[1]>=0):
        reducedmass,xvec,avec,t=ODEeq.timestepRK4ODE(i,dt)
        if printoutput:
            print(xvec[1])
        #print(ay) #forces should be equal and opposite, but in reduced mass framework accelerations are also equal and opposite
        #accelerations should evolve from y to x with time in a sinusoidal manner even in reduced mass framework
        #print(ax)
        xy=[xvec[1,0],xvec[1,1]]
        lastvalue,thisvalue=thisvalue, xy
        #lastvalue=thisvalue
        #thisvalue[0]=x[1]
        #thisvalue[1]=y[1]
        #thisvalue[0]=x[1]
        #thisvalue[1]=y[1]
        if printoutput:
            print(xy,lastvalue,thisvalue)
        i+=1
    
    print(thisvalue[0], thisvalue[1], lastvalue[0], lastvalue[1], x0, y0)
    return np.abs(x0-(thisvalue[0]+lastvalue[0])/2.)

In [15]:
dt=1 #*31556926 #seconds per year
numsteps=2000
mtotal,mass0,xvec,avec=xyuvaeqreducedmass
L0arr=[]
dtarr=[]
dtinit=0.125/4.
for i in np.arange(6):
    dt=(2**i)*dtinit
    dtarr.append(dt)
    L0=RunFirstOrbit(dt,xyuvaeqreducedmass,False)
    L0arr.append(L0)
print(dtarr, L0arr)

49.99999999953296 0.0002192859448121075 49.99999963631869 -0.0060307140405620845 50.0 0.0
49.99999988071706 0.003453927124506005 49.99999918169882 -0.009046072823391333 50.0 0.0
49.99999631800075 0.019188567850575995 49.99999966228481 -0.005811431665311891 50.0 0.0
49.99999901531124 0.009923209458593915 49.99998393852151 -0.04007678618495503 50.0 0.0
49.99997433783596 0.0506578421685326 49.99997565353719 -0.049342141156090036 50.0 0.0
49.99991647414743 0.09139244302314348 49.99988204414578 -0.10860742067949075 50.0 0.0
[0.03125, 0.0625, 0.125, 0.25, 0.5, 1.0] [1.820741744040788e-07, 4.6879205939376334e-07, 2.009857226425993e-06, 8.523083621980732e-06, 2.5004313428667047e-05, 0.00010074085339795147]


In [16]:
xdat=np.log10(np.array(dtarr))
ydat=np.log10(np.array(L0arr))

In [17]:
fitparam=np.polyfit(xdat,ydat,1)

In [18]:
fitparam

array([ 1.85300205, -4.01110848])

In [19]:
errfn=np.poly1d(fitparam)

In [20]:
errfn

poly1d([ 1.85300205, -4.01110848])

In [21]:
from bokeh.io import output_notebook, show
from bokeh.plotting import figure
output_notebook()
# create a new plot with default tools, using figure
p = figure(title="L0 error after one orbit, Circular, Vector, RK4", x_axis_label="dt", y_axis_label="L0", plot_width=400, plot_height=400)

# add a circle renderer with x and y coordinates, size, color, and alpha

p.circle(np.log10(np.array(dtarr)),np.log10(np.array(L0arr)), line_color="blue", legend="L0")
p.line(xdat,errfn(xdat),line_color="green", legend="Fit, dt^4.1")
p.legend.location = "bottom_right"
p.legend.click_policy="hide"

show(p) # show the

Loading BokehJS ...

%%html 
<a href="https://github.com/sdorsher/ManyBodyProblem/blob/master/L0%20error%20Circular%20Vector%20RK4%20dt%204p1.png"> L0 error after one circular orbit in the reduced mass sytem </a>

L0 error is the absolute value of the difference between the x coordinate at t=0 and the x coordinate after one orbit. I have plotted the behavior of the L0 error as a function of the timestep dt. For the RK4 numerical differential equation solution method, the error should go as dt^4 or better. It doe, since it goes as dt^4.1. 